// ─── Services ────────────────────────────────────────────────────────────────
export const services = [
  {
    slug: "seo",
    icon: "Search",
    title: "Search Engine Optimization",
    tagline: "Rank higher. Get found. Grow organically.",
    description: "We engineer SEO strategies that compound over time — driving qualified traffic, building authority, and turning search into your most reliable growth channel.",
    benefits: ["Technical SEO audits & fixes","Content strategy & optimization","Link building & authority growth","Local SEO for multi-location brands","Core Web Vitals optimization"],
    process: [
      { step: "01", title: "Audit", desc: "Deep technical & content audit of your current SEO health." },
      { step: "02", title: "Strategy", desc: "Custom roadmap targeting high-intent keywords and gaps." },
      { step: "03", title: "Execute", desc: "On-page, off-page, and technical implementation." },
      { step: "04", title: "Scale", desc: "Monthly reporting with continuous optimization loops." },
    ],
    metric: { value: "3.4×", label: "avg. organic traffic growth" },
    color: "blue",
  },
  {
    slug: "paid-ads",
    icon: "Target",
    title: "Paid Advertising",
    tagline: "Precision targeting. Maximum ROAS.",
    description: "From Google Search to Meta to YouTube, we build performance ad systems that turn ad spend into predictable revenue — not guesswork.",
    benefits: ["Google & Microsoft Ads","Meta (Facebook & Instagram) Ads","YouTube & Connected TV","Programmatic display","Retargeting & audience segmentation"],
    process: [
      { step: "01", title: "Research", desc: "Audience analysis, competitor intel, and keyword mapping." },
      { step: "02", title: "Build", desc: "Campaign architecture, creatives, and landing pages." },
      { step: "03", title: "Launch", desc: "Multi-platform deployment with tracking fully wired." },
      { step: "04", title: "Optimize", desc: "Weekly bid & creative optimization for peak ROAS." },
    ],
    metric: { value: "6.2×", label: "avg. return on ad spend" },
    color: "violet",
  },
  {
    slug: "social-media",
    icon: "Share2",
    title: "Social Media Marketing",
    tagline: "Build community. Drive engagement. Convert followers.",
    description: "We handle everything — strategy, content, posting, community management — so your brand shows up consistently and compellingly on every platform.",
    benefits: ["Multi-platform content strategy","Creative production & copywriting","Community management & DMs","Influencer identification & outreach","Monthly analytics & growth reporting"],
    process: [
      { step: "01", title: "Audit", desc: "Platform audit and competitor benchmarking." },
      { step: "02", title: "Plan", desc: "Monthly content calendar and creative direction." },
      { step: "03", title: "Create", desc: "Design, write, and produce all content assets." },
      { step: "04", title: "Grow", desc: "Publish, engage, and iterate based on data." },
    ],
    metric: { value: "280%", label: "avg. engagement rate lift" },
    color: "pink",
  },
  {
    slug: "cro",
    icon: "TrendingUp",
    title: "Conversion Rate Optimization",
    tagline: "More revenue from existing traffic.",
    description: "We systematically identify friction points and optimize your website and funnels so more visitors become customers — without spending more on ads.",
    benefits: ["Heuristic UX audits","A/B & multivariate testing","Landing page redesigns","Funnel analytics & heatmaps","Checkout & form optimization"],
    process: [
      { step: "01", title: "Research", desc: "Heatmaps, session recordings, and user interviews." },
      { step: "02", title: "Hypothesize", desc: "Prioritized test backlog based on impact/effort." },
      { step: "03", title: "Test", desc: "Rigorous A/B testing with statistical significance." },
      { step: "04", title: "Deploy", desc: "Winners rolled out; insights feed the next cycle." },
    ],
    metric: { value: "41%", label: "avg. conversion rate uplift" },
    color: "emerald",
  },
  {
    slug: "web-development",
    icon: "Code2",
    title: "Web Development",
    tagline: "Fast, beautiful, conversion-ready websites.",
    description: "We design and build high-performance websites and landing pages that look exceptional, load instantly, and are engineered to convert visitors into revenue.",
    benefits: ["Custom Next.js & React development","Landing page & funnel design","E-commerce storefronts (Shopify, custom)","CMS integration (Sanity, Contentful)","Core Web Vitals & performance optimization"],
    process: [
      { step: "01", title: "Discovery", desc: "Goals, audience, and technical requirements scoped." },
      { step: "02", title: "Design", desc: "High-fidelity wireframes and UI design reviewed with you." },
      { step: "03", title: "Build", desc: "Pixel-perfect development with full CMS integration." },
      { step: "04", title: "Launch", desc: "QA, performance audit, and go-live support." },
    ],
    metric: { value: "2.1s", label: "avg. page load time" },
    color: "cyan",
  },
];

export const projects = [
  {
    slug: "meridian-fintech",
    client: "Meridian",
    industry: "FinTech",
    title: "How Meridian grew MRR 340% in 8 months",
    summary: "A complete digital overhaul — SEO, paid ads, and CRO — turned Meridian's stagnant pipeline into a high-velocity growth engine.",
    services: ["SEO","Paid Ads","CRO"],
    image: "#e0e9ff",
    results: [
      { metric: "340%", label: "MRR Growth" },
      { metric: "6.8×", label: "ROAS" },
      { metric: "54%", label: "CVR Lift" },
    ],
    problem: "Meridian had a strong product but near-zero organic visibility and paid campaigns burning budget with <1.5× ROAS.",
    solution: "We rebuilt their Google Ads account architecture, launched a technical SEO sprint, and A/B tested 14 landing page variants over 6 months.",
    featured: true,
    tag: "FinTech",
  },
  {
    slug: "bloom-ecommerce",
    client: "Bloom",
    industry: "E-commerce",
    title: "Bloom's 290% organic revenue growth in one year",
    summary: "A content-led SEO strategy combined with social proof optimization doubled Bloom's organic channel within 12 months.",
    services: ["SEO","Social Media"],
    image: "#dcfce7",
    results: [
      { metric: "290%", label: "Organic Revenue" },
      { metric: "3.1×", label: "Organic Traffic" },
      { metric: "68K", label: "New Followers" },
    ],
    problem: "Bloom was entirely dependent on paid traffic. One iOS update nearly killed their business overnight.",
    solution: "We built a 200-article content moat, optimized 800+ product pages, and launched a creator partnership program.",
    featured: true,
    tag: "E-commerce",
  },
  {
    slug: "nova-saas",
    client: "Nova",
    industry: "SaaS",
    title: "Nova cuts CAC by 62% while scaling ad spend",
    summary: "A full-funnel paid media restructure and landing page testing program made Nova's acquisition economics dramatically more efficient.",
    services: ["Paid Ads","CRO"],
    image: "#f3e8ff",
    results: [
      { metric: "62%", label: "CAC Reduction" },
      { metric: "4.4×", label: "Trial Signups" },
      { metric: "89%", label: "Lead Quality Score" },
    ],
    problem: "Nova was spending $80K/mo on ads with a $420 CAC — far above their LTV-to-CAC target.",
    solution: "We rebuilt their entire paid funnel: new campaign structure, ICP-targeted creatives, and 3 CRO sprint cycles on trial signup pages.",
    featured: true,
    tag: "SaaS",
  },
  {
    slug: "apex-healthcare",
    client: "Apex Health",
    industry: "Healthcare",
    title: "Apex Health generates 5× more qualified leads",
    summary: "Local SEO and a targeted Google Ads strategy turned Apex Health into the dominant search presence across 6 metro markets.",
    services: ["SEO","Paid Ads"],
    image: "#fff7ed",
    results: [
      { metric: "5×", label: "Lead Volume" },
      { metric: "#1", label: "Local Pack Ranking" },
      { metric: "78%", label: "Cost Per Lead Drop" },
    ],
    problem: "Spread across 6 cities, Apex had no consistent local presence and was losing patients to better-ranked competitors.",
    solution: "We built a city-specific SEO strategy, optimized 6 Google Business Profiles, and ran hyper-local Google Search campaigns.",
    featured: false,
    tag: "Healthcare",
  },
];

export const blogPosts = [
  {
    slug: "seo-trends-2025",
    title: "The 7 SEO Trends That Will Define 2025",
    excerpt: "AI Overviews, zero-click searches, and E-E-A-T evolution — here's what to prioritize in your SEO strategy this year.",
    category: "SEO",
    readTime: "8 min",
    date: "April 14, 2025",
    author: { name: "Sarah Kim", role: "Head of SEO" },
    image: "#eff6ff",
    featured: true,
  },
  {
    slug: "meta-ads-creative-strategy",
    title: "Why Your Meta Ads Creative Is Costing You 40% More",
    excerpt: "Static creative is dying. Here's the performance creative framework we use to scale Meta campaigns to 8-figure spend.",
    category: "Paid Ads",
    readTime: "6 min",
    date: "April 7, 2025",
    author: { name: "James Park", role: "Head of Paid Media" },
    image: "#faf5ff",
    featured: true,
  },
  {
    slug: "cro-audit-checklist",
    title: "The 23-Point CRO Audit That Lifted Our Client's CVR 41%",
    excerpt: "A systematic approach to finding and fixing the conversion killers on your website. Free checklist included.",
    category: "CRO",
    readTime: "10 min",
    date: "March 28, 2025",
    author: { name: "Maya Torres", role: "CRO Lead" },
    image: "#f0fdf4",
    featured: false,
  },
  {
    slug: "social-media-b2b",
    title: "The B2B Social Media Playbook for 2025",
    excerpt: "LinkedIn isn't enough. Here's how high-growth B2B brands are building audience and pipeline on social in 2025.",
    category: "Social Media",
    readTime: "7 min",
    date: "March 20, 2025",
    author: { name: "Priya Nair", role: "Social Media Director" },
    image: "#fff7ed",
    featured: false,
  },
];

export const testimonials = [
  { quote: "Apex didn't just run our ads — they rebuilt our entire growth engine. 6.8× ROAS in month four was something we thought was impossible.", author: "Michael Chen", role: "CEO", company: "Meridian FinTech", initials: "MC", color: "#4a6cf7" },
  { quote: "Our organic revenue grew 290% in 12 months. The content strategy they built is now our most valuable business asset.", author: "Jessica Hall", role: "CMO", company: "Bloom Commerce", initials: "JH", color: "#10b981" },
  { quote: "They cut our CAC by 62% while we tripled our ad budget. I didn't think both were possible at the same time. They proved me wrong.", author: "Raj Patel", role: "VP Growth", company: "Nova SaaS", initials: "RP", color: "#7c3aed" },
  { quote: "The CRO work alone paid for the entire annual retainer in the first month. Everything after that is pure profit.", author: "Lisa Wang", role: "Director of Marketing", company: "Apex Health", initials: "LW", color: "#f59e0b" },
];

export const team = [
  { name: "Alex Morgan", role: "Founder & CEO", bio: "15 years in growth marketing. Previously VP Marketing at two unicorn startups.", color: "#4a6cf7" },
  { name: "Sarah Kim", role: "Head of SEO", bio: "Former Google Search Quality Analyst. Obsessed with topical authority.", color: "#10b981" },
  { name: "James Park", role: "Head of Paid Media", bio: "Managed $50M+ in ad spend across Google, Meta, and programmatic.", color: "#7c3aed" },
  { name: "Maya Torres", role: "CRO Lead", bio: "Behavioral economist turned conversion strategist. 300+ A/B tests run.", color: "#f59e0b" },
  { name: "Priya Nair", role: "Social Media Director", bio: "Built social programs for 5 brands that hit 1M+ followers.", color: "#ef4444" },
  { name: "Tom Lee", role: "Head of Analytics", bio: "Former data scientist at Meta. Turns raw data into revenue insights.", color: "#06b6d4" },
];

export const stats = [
  { value: "300+", label: "Clients Served" },
  { value: "$2.4B", label: "Revenue Generated" },
  { value: "6.2×", label: "Avg. ROAS" },
  { value: "98%", label: "Client Retention" },
];
